# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp

  # Firebase Native SDKs (Required by GitLive)
  # GitLive Firebase SDK wraps these native implementations
  # See: https://github.com/GitLiveApp/firebase-kotlin-sdk
  pod 'FirebaseCore'      # Core Firebase - Required
  pod 'FirebaseAuth'      # Authentication - Required by dev.gitlive:firebase-auth
  pod 'FirebaseDatabase'  # Realtime Database - Required by dev.gitlive:firebase-database
  pod 'FirebaseStorage'   # Cloud Storage - Required by dev.gitlive:firebase-storage

  # Google Sign-In
  # Required because GitLiveAuthRepository uses GoogleAuthProvider
  pod 'GoogleSignIn'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
